Jest package update, simple tests for Alert component
brewkit/components pull request #111
Opened 2021-05-12 09:41 UTC by kbulatovic

## Description
Updated some deps for ts, jest bridge stuff.
Created a simple test cases for Alert component. 
Didn't cover the Material UI abstraction props, since they themselves cover them, so we rely on them to just work. 
IMO our test cases should just cover custom changes on the components.

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2021-05-13 14:06 UTC, ItsEricWoodward approved these changes

2021-05-18 15:02 UTC, emdrayallday requested changes
I see you removed a lot of double spacing, this is intentional. We want to separate sections with double spacing and content within a section by single space, just to make things more readable and deliberate.

```
import React from 'react';
import MuiAlert from '@material-ui/lab/Alert';
// 2 empty lines
// 
const Alert = ({
    ...props
}) => {
// 2 empty lines
// 
    const [state, setState] = React.useState('state');
    const [otherState, setOtherState] = React.useState('otherState');
// 2 empty lines
// 
   const handlerFunction = () => {
         // function stuff
    }
    // 1 empty line b/c these are similar but need to be separated to make it more clear
   const otherFunction = () => {
        // other function stuff
    }
// 2 empty lines
// 
    return (
         JSX
    );
}
// 2 empty lines
// 
export default Alert;

2021-05-21 13:28 UTC, emdrayallday commented on src/components/CircularProgress/stories.tsx
> +        jest: ['CirularProgress.test']
typo

2021-05-21 13:38 UTC, lawren commented
@kbulatovic, I updated Storybook which changed some of the story formatting. That's most likely where the conflicts are coming from there. You should just have to re-add the jest config to the story parameters.

2021-09-09 19:24 UTC, ItsEricWoodward commented
I'm closing this PR because of its age and size. I like where this is going, and I encourage you to resubmit it in smaller chunks, and with the conflicts resolved. Thanks!

2021-09-09 19:24 UTC, closed without merging