Feat/ovrc 12831
brewkit/components pull request #167
Opened 2021-10-14 13:53 UTC by kbulatovic

- Removed obsolete testing deps
 - Created dedicated config file for jest, enzyme
 - Bumped deps for jest, enzyme
 - Created test for `<Alert />`, changed structure for more clearer IDE experience
 - Added Majestic UI for jest tests, dedicated command

2021-10-18 14:12 UTC, emdrayallday requested changes

2021-10-18 14:12 UTC, emdrayallday commented on src/components/Badge/Badge.tsx
> + * > No differences in Brewkit.
Why would we add this if there are no differences?

2021-10-19 16:51 UTC, ItsEricWoodward commented on src/components/Button/Button.spec.tsx
> +})
Fixed.

2021-10-19 16:53 UTC, ItsEricWoodward approved these changes

2021-10-19 16:58 UTC, merged