fixed nested issue
brewkit/components pull request #189
Opened 2021-11-23 17:53 UTC by beahoop

## Description

## Types of changes

- [ x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2021-11-23 23:26 UTC, ItsEricWoodward requested changes
👍 apart from the `console.log`. Excise that and you'll be good to go.

2021-11-23 23:26 UTC, ItsEricWoodward commented on src/components/FormField/FormField.tsx
> +            console.log(isError)
I think you forgot to remove this.

2021-11-24 15:24 UTC, emdrayallday requested changes
Close but not quite.

you should probably name the error message better if it has one. isError doesn't really make sense to me. I would just name it errorMessage.

then for the error attribute on the <Component you need to check if there is an error, not an error message

2021-11-24 15:24 UTC, emdrayallday commented on src/components/FormField/FormField.tsx
> +            error={_.get(errors, `${name}[message]`)}
This isn't right, what happens when there isn't a message but still an error?

2021-11-24 15:24 UTC, emdrayallday commented on src/components/FormField/FormField.tsx
> +import _ from 'lodash';
destructure

2021-11-24 15:34 UTC, emdrayallday commented on src/components/FormField/FormField.tsx
> +        const isError = _.get(errors, `${name}[message]`);
also instead of [message] do `${name}.message`

2021-11-24 16:43 UTC, emdrayallday approved these changes

2021-11-24 16:43 UTC, merged