Icons
brewkit/components pull request #239
Opened 2022-01-13 19:50 UTC by alyssadee

## Description
SvgIcon creation for custom icons

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2022-01-13 21:16 UTC, ItsEricWoodward approved these changes

2022-01-13 23:02 UTC, ItsEricWoodward requested changes
It all looks good except that you need to build and commit the updated JS and `.d.ts` files for this component's theme as well.

Can you please run `npm run build-themes` and add the updated files to this PR?

Thanks!

2022-01-14 21:23 UTC, alyssadee commented
@ItsEricWoodward Running that command doesn't do anything for me.. where are those files supposed to be generated?

2022-01-14 21:31 UTC, ItsEricWoodward approved these changes

2022-01-14 21:33 UTC, merged

2022-01-20 18:00 UTC, ItsEricWoodward commented
:tada: This PR is included in version 4.9.0 :tada:

The release is available on [GitHub release](https://github.com/brewkit/components/releases/tag/v4.9.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: